on: 
    push:
        branches: ["main"]


name:  Ftp-Deploy-Action
jobs:
 FTP-Deploy-Action:
     name: FTP-Deploy-Action
     runs-on: ubuntu-latest
     steps:
   
     - uses: actions/checkout@v4
       with:
         fetch-depth: 2
     - name: FTP-Deploy-Action
       uses: airvzxf/ftp-deployment-action@latest
       with:
         server: ftp://103.195.4.8
         username: RestroReff
         password: ${{ secrets.PROD_FTP_PASSWORD}}
         local_dir: "./testFTP.html"
         remote_dir: "https://restroreff.microlent.com/poc/"
