on: 
    push:
        branches: ["main"]


name:  Ftp-Deploy-Action
jobs:
 FTP-Deploy-Action:
     name: FTP-Deploy-Action
     runs-on: ubuntu-latest
     steps:
   
     - uses: actions/checkout@v4
       with:
         fetch-depth: 2
     - name: FTP-Deploy-Action
       uses: SamKirkland/FTP-Deploy-Action@v4.3.5
       with:
         server: ftp://103.195.4.8
         username: RestroReff
         password: ${{ secrets.ftp_password }}